# variables.tf for Lab 16: Host Session Project Implementation
# Generated by Copilot

variable "project_id" {
  description = "The GCP project ID where resources will be created"
  type        = string
}

variable "region" {
  description = "The GCP region for resources"
  type        = string
  default     = "us-central1"
}

variable "zone" {
  description = "The GCP zone for zonal resources"
  type        = string
  default     = "us-central1-a"
}

variable "create_host_project" {
  description = "Whether to create a new host session project"
  type        = bool
  default     = false
}

variable "host_project_name" {
  description = "Name for the host session project"
  type        = string
  default     = "Host Session Project"
}

variable "host_project_id" {
  description = "Project ID for the host session project"
  type        = string
}

variable "billing_account" {
  description = "Billing account ID for the host session project"
  type        = string
  default     = ""
}

variable "folder_id" {
  description = "Folder ID where the host session project will be created"
  type        = string
  default     = ""
}

variable "required_apis" {
  description = "List of APIs to enable in the host session project"
  type        = list(string)
  default = [
    "compute.googleapis.com",
    "oslogin.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "iam.googleapis.com",
    "cloudresourcemanager.googleapis.com"
  ]
}

variable "host_session_vpc_name" {
  description = "Name for the host session VPC network"
  type        = string
  default     = "host-session-vpc"
}

variable "host_session_subnet_name" {
  description = "Name for the host session subnet"
  type        = string
  default     = "host-session-subnet"
}

variable "host_session_subnet_cidr" {
  description = "CIDR range for the host session subnet"
  type        = string
  default     = "10.0.0.0/24"
}

variable "secondary_ip_ranges" {
  description = "Secondary IP ranges for the subnet"
  type = list(object({
    range_name    = string
    ip_cidr_range = string
  }))
  default = []
}

variable "ssh_source_ranges" {
  description = "Source IP ranges allowed for SSH access"
  type        = list(string)
  default     = ["10.0.0.0/8"]
}

variable "rdp_source_ranges" {
  description = "Source IP ranges allowed for RDP access"
  type        = list(string)
  default     = ["10.0.0.0/8"]
}

variable "host_session_admin_members" {
  description = "List of members to grant host session admin roles"
  type        = list(string)
  default     = []
}

variable "host_session_user_members" {
  description = "List of members to grant host session user roles"
  type        = list(string)
  default     = []
}

variable "create_sample_vm" {
  description = "Whether to create a sample VM instance"
  type        = bool
  default     = false
}

variable "sample_vm_name" {
  description = "Name for the sample VM instance"
  type        = string
  default     = "host-session-vm"
}

variable "sample_vm_machine_type" {
  description = "Machine type for the sample VM"
  type        = string
  default     = "e2-medium"
}

variable "sample_vm_image" {
  description = "Boot disk image for the sample VM"
  type        = string
  default     = "ubuntu-os-cloud/ubuntu-2004-lts"
}

variable "sample_vm_disk_size" {
  description = "Boot disk size in GB for the sample VM"
  type        = number
  default     = 20
}

variable "sample_vm_service_account_email" {
  description = "Service account email for the sample VM"
  type        = string
  default     = ""
}

variable "enable_oslogin" {
  description = "Enable OS Login for instances"
  type        = bool
  default     = true
}

variable "network_tags" {
  description = "Network tags to apply to instances"
  type        = list(string)
  default     = ["host-session"]
}

variable "labels" {
  description = "Labels to apply to resources"
  type        = map(string)
  default = {
    environment = "host-session"
    lab         = "lab-16"
  }
}
